Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -40,32 +40,32 @@ jobs:
       # Your project will need to have tests in test/ and a dependency on
       # package:test for this step to succeed. Note that Flutter projects will
       # want to change this to 'flutter test'.--coverage reports/coverage
-      - name: Test
-        run: dart test --file-reporter json:reports/tests.json 
+#       - name: Test
+#         run: dart test --file-reporter json:reports/tests.json 
 
-      - name: Test Reporter
-        uses: dorny/test-reporter@v1.4.3
-        if: success() || failure() 
-        with:
-          name: Dart Tests
-          path: reports/*.json
-          reporter: dart-json
+#       - name: Test Reporter
+#         uses: dorny/test-reporter@v1.4.3
+#         if: success() || failure() 
+#         with:
+#           name: Dart Tests
+#           path: reports/*.json
+#           reporter: dart-json
 
-      - name: fudge coverage of missed files
-        uses: stelynx/dart-full-coverage@v1.0.5
-        if: success() || failure() 
-        with:
-          package: get_comics
-      - name: run coverage
-        if: success() || failure() 
-        run: dart run test --coverage=coverage
-      - name: report coverage
-        uses: zgosalvez/github-actions-report-lcov@v1
-        if: success() || failure() 
-        with:
-          coverage-files: coverage/lcov*.info
-          artifact-name: code-coverage-report
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+#       - name: fudge coverage of missed files
+#         uses: stelynx/dart-full-coverage@v1.0.5
+#         if: success() || failure() 
+#         with:
+#           package: get_comics
+#       - name: run coverage
+#         if: success() || failure() 
+#         run: dart run test --coverage=coverage
+#       - name: report coverage
+#         uses: zgosalvez/github-actions-report-lcov@v1
+#         if: success() || failure() 
+#         with:
+#           coverage-files: coverage/lcov*.info
+#           artifact-name: code-coverage-report
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
       - name: Build
         run: dart compile exe -o get-comics-x86-64 bin/get_comics.dart
       - name: Release
